global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Endereço do serviço Prometheus

  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']  # Endereço do serviço Django

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] # Endereço do serviço cadvisor

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # Endereço do serviço node-exporter

rule_files:
  - alert_rules.yaml