FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY tools/wait-for-it.sh /wait-for-it.sh
COPY tools/script.sh /script.sh

RUN chmod +x /wait-for-it.sh && chmod +x /script.sh


# CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["/wait-for-it.sh", "django:8000", "--timeout=20", "--strict", "--", "./script.sh"]