name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Installing docker
        run: curl -fsSL https://get.docker.com/ | sh
        
      - name: Create env_file
        run: |
          echo "DB_HOST=${DB_HOST}" > ./docker/src/.env
          echo "DB_USER=${DB_USER}" >> ./docker/src/.env
          echo "DB_NAME=${DB_NAME}" >> ./docker/src/.env
          echo "DB_PORT=${DB_PORT}" >> ./docker/src/.env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> ./docker/src/.env
  
      - name: install make
        run: sudo apt-get install make
        
      - name: Make
        working-directory: ./docker
        run: |
          pwd
          ls -la
          make

      - name: Uptest
        run: curl http://localhost:8000
