# Paths are relative to docker-compose.yml, not Makefile

volumes:
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../django

  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../postgres_data

networks:
  ft_transcendence:
    name: ft_transcendence

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft_transcendence

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - ft_transcendence

  django:
    container_name: django
    build: requirements/django
    env_file: .env
    restart: always
    volumes:
      - django:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - ft_transcendence
